Allow walkthroughs on modal view controllers
ruipfcosta/SwiftyWalkthrough pull request #2
Opened 2016-10-12 10:13 UTC by ChristopheFernandes

@ruipfcosta I propose this update to allow walkthroughs on modal presented from root view controller

2016-10-12 19:38 UTC, ruipfcosta requested changes

2016-10-12 19:38 UTC, ruipfcosta commented on Sources/UIViewController+Walkthrough.swift
> +        if let presentedViewController = rootController?.presentedViewController {
Can we just change this to `return rootController?.presentedViewController ?? rootController `

2016-10-12 19:39 UTC, ruipfcosta commented
Thanks @ChristopheFernandes!

2016-10-13 07:10 UTC, ChristopheFernandes commented
@ruipfcosta done ! ;)

2016-10-14 15:44 UTC, ruipfcosta requested changes

2016-10-14 15:44 UTC, ruipfcosta commented on Sources/Info.plist
> +	<string>0.0.4</string>
The version bump should be kept separate from this feature. Can you revert this change please?

2016-10-14 15:44 UTC, ruipfcosta commented on SwiftyWalkthrough.podspec
> -  s.version      = "0.0.3"
Same comment as before regarding version bump.

2016-10-14 15:54 UTC, ChristopheFernandes commented
@ruipfcosta it's done.

2016-10-14 21:56 UTC, ruipfcosta approved these changes

2016-10-14 21:56 UTC, merged

2016-10-14 23:59 UTC, ruipfcosta commented
It seems this wasn't that easy - have a look at https://github.com/ruipfcosta/SwiftyWalkthrough/commit/52b1072bb58950e8c72c20df662f1915a5c8d435 and check if suits your needs.

2016-10-17 15:53 UTC, ChristopheFernandes commented
It's seems to be ok ! Sorry I can't test I didn't migrate my app to swift 3.0.